networks:
  network2:
    name: network2
services:
  nginx2:
    container_name: nginx2
    image: nginx:1.27
    ports:
      - 80:80
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/public_html
    networks:
      - network2
    depends_on:
      - php2
      - mysgl2
  php2:
    container_name: php2
    build: ./images/php
    volumes:
      - ./www:/var/www/public_html
    networks:
      - network2
    depends_on:
      - mysgl2
  mysgl2:
    container_name: mysql2
    image: mysql:8.0
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=Sergeiuser
      - MYSQL_PASSWORD=Sergeipass
    networks:
      - network2
  phpmyadmin2:
    container_name: phpmyadmin2
    image: phpmyadmin:5.2
    ports:
      - 1500:80
    environment:
      - PMA_HOST=mysql2
    networks:
      - network2
    depends_on:
      - mysgl2
