version: '3.9'
services:
  nginx2:
    image: nginx:1.27-alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/public_html
    networks:
      - network2
  php2:
    build: ./images/php
    restart: unless-stopped
    volumes:
      - ./www:/var/www/public_html
    networks:
      - network2
  mysql2:
    image: mysql:8.0
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - network2
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
  phpmyadmin2:
    image: phpmyadmin:5.2
    restart: unless-stopped
    ports:
      - 1500:80
    environment:
      - PMA_HOST=mysql2
    networks:
      - network2

networks:
  network2:

volumes:
  mysql_data: